### ISSUE TITLE
vocal_diagnose function use failure

### ISSUE THREAD

**Issue by Doniol-Valcroze** [dbssyck/tanysiptera#1]
Dear authors,

I've tried to use your tanysiptera package to calculate Isler criterions on Pipit (genus Anthus) call measurments but after installing the package and read the **?vocal_diagnose** help page, the **vocal_diagnose** function is not found and even the test/example can't run. Could you check your package to resolve this issue or explain how to use your package?

Thank in advance,

Paul

**Comment by dbssyck** [comment]
Dear Paul,

Thank you for using this package and for reporting the issue. I've pushed a Github update, could you please reinstall the package and try the test file using the code below please?

```
test <- read.table(system.file ("extdata", "test_data.txt", package = "tanysiptera"), header = TRUE) 
vocal_diagnose(test)
```

Thank you very much.

Keita

**Comment by Doniol-Valcroze** [comment]
Dear Keita,

The function is now working perfectly, thank you for your quick answer!

Bests,

Paul
